In [22]:
import numpy as np

In [26]:
# Function for creating zero arrays
zerosArray = np.zeros(10)
print(zerosArray) # It prints out float values. We'd need to convert 'm

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
# We'd need to convert 'm into integer values
print(zerosArray.astype(int))

[0 0 0 0 0 0 0 0 0 0]


In [34]:
# Function for creating ones arrays
onesArray = np.ones(10)
print(onesArray.astype(int)) # It prints out float values. We'd need to convert 'm

[1 1 1 1 1 1 1 1 1 1]


In [36]:
# Function for creating different array values
preFilledArray = np.full(10,5)
print(preFilledArray.astype(int)) # It prints out float values. We'd need to convert 'm

[5 5 5 5 5 5 5 5 5 5]


In [44]:
# Using scalar values. It's useful for incrementing values in the elements of the arrays. 
# Note: In plane python this functionality doesn't work
matrix = np.matrix([[1,2,3],[4,5,6]])
print(matrix)
print(matrix + 1)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [46]:
# Using scalar values. Decrement the value of those elements
print(matrix - 3)

[[-2 -1  0]
 [ 1  2  3]]


In [48]:
# Using scalar values. Multipy the value of those elements
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [52]:
# Using scalar values. Divide the value of those elements
print(matrix // 2) # Just one / is for float and // is for integers

[[0 1 1]
 [2 2 3]]


In [54]:
# Using the transpose option
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [56]:
# Usint matmul to multiply values
# For instance: np.matmul(matrix1, matrix2)

In [68]:
# Statistic functions. There are tons of those: https://numpy.org/doc/2.2/reference/routines.statistics.html
np.min(matrix)

1

In [66]:
np.max(matrix)

6

In [70]:
np.sum(matrix)

21

In [74]:
np.mean(matrix) # Average of an array

3.5

In [76]:
np.std(matrix) # Finds the standar diviation of an array

1.707825127659933

In [78]:
np.median(matrix) # Gives the medium value of an array

matrix([[1., 2., 3., 4., 5., 6.]])