#############################################
# NUMPY
#############################################

# Why Numpy?
# Creating Numpy Arrays
# Attibutes of Numpy Arrays
# Reshaping
# Index Selection
# Slicing
# Fancy Index
# Conditions on Numpy
# Mathematical Operations

#############################################
# Why Numpy?
#############################################


In [3]:
# importing numpy
import numpy as np


In [4]:
# Using lists
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a * b

array([ 2,  6, 12, 20])

In [5]:
#############################################
# Creating Numpy Arrays
#############################################

np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))
np.zeros(10, dtype=int)
np.random.randint(0, 10, size=10)
np.random.normal(10, 4, (3, 4))

array([[13.72094258,  8.63392695,  9.21692676, 10.0635528 ],
       [ 9.26052316,  8.77826299,  2.34517604,  6.19374315],
       [ 9.63399251, 14.00758327, 13.35462249,  8.54083121]])

In [6]:
#############################################
# Attibutes of Numpy Arrays
#############################################

# ndim: number of dimensions (dimensionality)
# shape: shape (dimension information)
# size: total number of elements
# dtype: data type of the array

a = np.random.randint(10, size=5)
a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [7]:
#############################################
# Reshaping
#############################################

np.random.randint(1, 10, size=9)
np.random.randint(1, 10, size=9).reshape(3, 3)

ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)

array([[8, 2, 5],
       [7, 1, 2],
       [7, 7, 7]])

In [8]:
#############################################
# Index Selection
#############################################
a = np.random.randint(10, size=10)
a[0]
a[0:5]
a[0] = 999

m = np.random.randint(10, size=(3, 5))

m[0, 0]
m[1, 1]
m[2, 3]

m[2, 3] = 999

m[2, 3] = 2.9

m[:, 0]
m[1, :]
m[0:2, 0:3]

array([[5, 4, 3],
       [6, 7, 6]])

In [9]:
#############################################
# Fancy Index
#############################################

v = np.arange(0, 30, 3)
v[1]
v[4]

catch = [1, 2, 3]

v[catch]

array([3, 6, 9])

In [10]:
#############################################
# Conditions on Numpy
#############################################
v = np.array([1, 2, 3, 4, 5])

#######################
# With For Loop
#######################
ab = []
for i in v:
    if i < 3:
        ab.append(i)

#######################
# With Numpy
#######################
v < 3

v[v < 3]
v[v > 3]
v[v != 3]
v[v == 3]
v[v >= 3]

array([3, 4, 5])

In [11]:
#############################################
# Mathematical Operations
#############################################
v = np.array([1, 2, 3, 4, 5])

v / 5
v * 5 / 10
v ** 2
v - 1

np.subtract(v, 1)
np.add(v, 1)
np.mean(v)
np.sum(v)
np.min(v)
np.max(v)
np.var(v)
v = np.subtract(v, 1)

In [12]:
#######################
# Solving Two Unknowns Equations with NumPy
#######################

# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

np.linalg.solve(a, b)

array([1.85714286, 2.71428571])